title: Michael Heironimus
email: heironimus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Heironimus's public technology work.
baseurl: "" # path under the root if you're in a subdir
url: "https://mkheironimus.github.io" # root URL
github_username: mkheironimus
twitter_username: mkheironimus
instagram_username: mkheironimus
imgur_username: mkheironimus
gems: # coffeescript and paginate plugins are default for github pages
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# seo-tag plugin - twitter handle
author: mkheironimus
twitter:
  username: mkheironimus
