title: Michael Heironimus
email: heironimus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Heironimus's public technology work.
baseurl: "" # path under the root if you're in a subdir
url: "http://mkheironimus.github.io" # root URL
github_username: mkheironimus
